all:bubblesort selectionsort insertionsort

bubblesort:bubblesort.c
	gcc bubblesort.c headerfile.c -o bubblesort
selectionsort:selectionsort.c
	gcc selectionsort.c headerfile.c -o selectionsort
insertionsort:insertionsort.c
	gcc insertionsort.c headerfile.c -o insertionsort
bubblestring:bubblestring.c
	gcc bubblestring.c headerfile.c -o bubblestring
selectionstring:selectionstring.c
	gcc selectionstring.c headerfile.c -o selectionstring
insertionstring:insertionstring.c
	gcc insertionstring.c headerfile.c -o insertionstring
clean:
	rm -f bubblesort selectionsort insertiosort bubblestring selectionstring  insertionstring





